### PR TITLE
[c#] Fix alias conversion issue for generic field

### LINKED ISSUE #928: Is the type alias converter in conjunction with generic fields not supported?
I've modified the `schema.bond` from the `example/cs/core/date_time`  project to include a generic like so:
```
namespace Examples

using DateTime = int64;

struct Wrapper<T> {
    0: T Value;
}

struct Example
{
    0: DateTime Now;
    1: vector<DateTime> Dates;
    2: Wrapper<DateTime> Date;
}
```

But if I try to serialize this I get an exception:
```
System.InvalidOperationException: The binary operator NotEqual is not defined for the types 'System.DateTime' and 'System.Int64'.
   at System.Linq.Expressions.Expression.GetEqualityComparisonOperator(ExpressionType binaryType, String opName, Expression left, Expression right, Boolean liftToNull)
   at System.Linq.Expressions.Expression.NotEqual(Expression left, Expression right)
   at Bond.Expressions.ObjectParser.Field(ITransform transform, Expression structVar, UInt16 id, ISchemaField schemaField, IField field) in C:\dev\vendor\bond\cs\src\core\expressions\ObjectParser.cs:line 169
   at Bond.Expressions.ObjectParser.<>c__DisplayClass21_0.<Apply>b__4(<>f__AnonymousType0`2 <>h__TransparentIdentifier0, IField knownField) in C:\dev\vendor\bond\cs\src\core\expressions\ObjectParser.cs:line 88
   at System.Linq.Enumerable.<SelectManyIterator>d__23`3.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at Bond.Expressions.ObjectParser.Apply(ITransform transform) in C:\dev\vendor\bond\cs\src\core\expressions\ObjectParser.cs:line 84
   at Bond.Expressions.SerializerTransform`2.Struct(IParser parser, RuntimeSchema schema, Boolean isBase) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 173
   at Bond.Expressions.SerializerTransform`2.Struct(IParser parser, RuntimeSchema schema) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 165
   at Bond.Expressions.SerializerTransform`2.<>c__DisplayClass12_0.<GenerateSerialize>b__0(IParser p) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 146
   at Bond.Expressions.SerializerGenerator`2.GenerateSerialize(Serialize serialize, IParser parser, ParameterExpression writer, Boolean inline) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 59
   at Bond.Expressions.SerializerTransform`2.GenerateSerialize(SerializeWithSchema serializeWithSchema, IParser parser, RuntimeSchema schema) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 155
   at Bond.Expressions.SerializerTransform`2.Value(IParser parser, Expression valueType, RuntimeSchema schema) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 334
   at Bond.Expressions.SerializerTransform`2.<>c__DisplayClass15_1.<Struct>b__6(IParser fieldParser, Expression fieldType) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 181
   at Bond.Expressions.Field.Bond.Expressions.IField.Value(IParser parser, Expression valueType) in C:\dev\vendor\bond\cs\src\core\expressions\Transform.cs:line 38
   at Bond.Expressions.ObjectParser.Field(ITransform transform, Expression structVar, UInt16 id, ISchemaField schemaField, IField field) in C:\dev\vendor\bond\cs\src\core\expressions\ObjectParser.cs:line 125
   at Bond.Expressions.ObjectParser.<>c__DisplayClass21_0.<Apply>b__4(<>f__AnonymousType0`2 <>h__TransparentIdentifier0, IField knownField) in C:\dev\vendor\bond\cs\src\core\expressions\ObjectParser.cs:line 88
   at System.Linq.Enumerable.<SelectManyIterator>d__23`3.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at Bond.Expressions.ObjectParser.Apply(ITransform transform) in C:\dev\vendor\bond\cs\src\core\expressions\ObjectParser.cs:line 84
   at Bond.Expressions.SerializerTransform`2.Struct(IParser parser, RuntimeSchema schema, Boolean isBase) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 173
   at Bond.Expressions.SerializerTransform`2.Struct(IParser parser, RuntimeSchema schema) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 165
   at Bond.Expressions.SerializerTransform`2.<>c__DisplayClass12_0.<GenerateSerialize>b__0(IParser p) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 146
   at Bond.Expressions.SerializerGenerator`2.GenerateSerialize(Serialize serialize, IParser parser, ParameterExpression writer, Boolean inline) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 77
   at Bond.Expressions.SerializerTransform`2.GenerateSerialize(SerializeWithSchema serializeWithSchema, IParser parser, RuntimeSchema schema) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 155
   at Bond.Expressions.SerializerTransform`2.Generate(IParser parser) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 125
   at Bond.Serializer`1.SerializerHelper..ctor(ObjectParser parser, Type type, Boolean inlineNested) in C:\dev\vendor\bond\cs\src\core\Serializer.cs:line 140
   at Bond.Serializer`1.TwoPassSerializerHelper`1..ctor(ObjectParser parser, Type type, Boolean inlineNested) in C:\dev\vendor\bond\cs\src\core\Serializer.cs:line 157
```

Is this not a supported use-case?

### PR DESCRIPTION
**Pull request by ara-ayvazyan**
Fixes #928.

### CODE REVIEW

**Comment by lalo** [comment]
Maybe we should add test in  cs/test/expressions/schemas.bond

and maybe cs/test/core/ConvertTests.cs

that one last test makes sure to count how many times converts gets called. We had an issue where 1 serialization caused 3 executions of the convert method. Since this is adding new behavior of another thing that gets converted, it'd be nice to check if its minimal work.

File: cs/test/expressions/SerializeCB.expressions [hunk 1]
```diff
@@ -1199,6 +1199,72 @@
...
+                .Block(ExpressionsTest.GenericNothing`1[System.DateTime] $GenericNothing`1_obj) {
+                    $GenericNothing`1_obj = (ExpressionsTest.GenericNothing`1[System.DateTime])$obj;
+                    .Call $writer.WriteStructBegin(.Constant<Bond.Metadata>(GenericNothing<int64>));
+                    .If ($GenericNothing`1_obj.value != null) {
+                        .Block() {
+                            .Call $writer.WriteFieldBegin(
+                                .Constant<Bond.BondDataType>(BT_INT64),
+                                .Constant<System.UInt16>(0),
+                                .Constant<Bond.Metadata>(value));
+                            .Call $writer.WriteInt64((System.Int64).Call ExpressionsTest.BondTypeAliasConverter.Convert(
```
Comment (ara-ayvazyan) [inline cs/test/expressions/SerializeCB.expressions]: It looks like we can avoid calling the `Convert` for `T?` (an extra overload) and delegate to existing version that expect `T` since the above check for `null`?

File: cs/test/expressions/Clone.expressions [hunk 2]
```diff
@@ -809,6 +809,46 @@
...
+                    $obj = (System.Object)$Example_obj._dt;
+                    .Block() {
+                        .Block(ExpressionsTest.Generic`1[System.DateTime] $Generic`1_obj) {
+                            $Generic`1_obj = (ExpressionsTest.Generic`1[System.DateTime])$obj;
+                            .Default(System.Void);
+                            .If ($Generic`1_obj.value != .Call ExpressionsTest.BondTypeAliasConverter.Convert(
+                                0L,
+                                .Default(System.DateTime))) {
+                                ($Example_result._dt).value = .Call ExpressionsTest.BondTypeAliasConverter.Convert(
+                                    .Call ExpressionsTest.BondTypeAliasConverter.Convert(
```
Comment (lalo) [inline cs/test/expressions/Clone.expressions]: I'm trying to decipher if we are calling convert() unnecesary too many times. We do one when comparing on if with a dummy value just to get the type check, then it looks like we call twice here? looks like a nested convert but it does not make sense. I'm not sure, thoughts?

Comment (ara-ayvazyan) [reply cs/test/expressions/Clone.expressions]: This is unrelated to this change. Same can be seen at [448-452](https://github.com/ara-ayvazyan/bond/blob/2fb352f12815603d735ec693b374310768c5c96b/cs/test/expressions/Clone.expressions#L448-L452).

Comment (lalo) [reply cs/test/expressions/Clone.expressions]: True.

Comment (ara-ayvazyan) [reply cs/test/expressions/Clone.expressions]: Actually, I'm not sure which value must be compared with: `default(int64)` or `default(DateTime)`, since the user-defined conversion may not map these values.

**Comment by ara-ayvazyan** [comment]
@chwarr, can you take a look if you get some time?

File: cs/src/core/expressions/ObjectParser.cs [hunk 3]
```diff
@@ -143,30 +143,36 @@ Expression Field(ITransform transform, Expression structVar, UInt16 id, ISchemaF
...
-                        : Expression.NotEqual(ContainerCount(fieldValue), Expression.Constant(0));
+                    cannotOmit = Expression.NotEqual(ContainerCount(fieldValue), Expression.Constant(0));
                 }
                 else
                 {
-                    cannotOmit = Expression.NotEqual(fieldValue, Expression.Constant(defaultValue));
+                    cannotOmit = Expression.NotEqual(
+                        fieldValue,
+                        defaultValue.GetType() != fieldValue.Type
+                            ? (Expression)Expression.Default(fieldValue.Type)
```
Comment (chwarr) [inline cs/src/core/expressions/ObjectParser.cs]: Minor: may be slightly clearer to structure this as:

```csharp
Expression comparand = defaultValue.GetType() != fieldValue.Type
                            ? (Expression)Expression.Default(fieldValue.Type)
                            : Expression.Constant(defaultValue);
cannotOmit = Expression.NotEqual(fieldValue, comparand);
```
